services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
      target: ${CLIENT_TARGET}
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./Client/src/:/app/src/
      - ./Client/public/:/app/public/

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
      target: ${SERVER_TARGET}
      args:
        - BUILD_CONFIGURATION=$BUILD_CONFIGURATION
        - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
    environment:
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
    ports:
      - "80:8080"
      - "443:8081"
    depends_on:
      - client
      - db
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
