services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
      target: ${CLIENT_TARGET:-client-development}
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./Client/src/:/app/src/
      - ./Client/public/:/app/public/

  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
      target: ${SERVER_TARGET:-server-development}
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-debug}
        - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Development}
      - DB_PASSWORD="${DB_PASSWORD:-zaq1@WSX}"
    ports:
      - "80:8080"
      - "443:8081"
    depends_on:
      - client
      - db
    networks:
      - app-network
    volumes:
      - ./Server/src/Migrations/:/Server/Migrations

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${DB_PASSWORD:-zaq1@WSX}"
      MYSQL_USER: "10001:10001"
      MYSQL_PASS: "${DB_PASSWORD:-zaq1@WSX}"
      ACCEPT_EULA: "Y"
    user: "10001:10001"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - ./DB/:/var/opt/mssql/

networks:
  app-network:
    driver: bridge
