const API = process.env.API
import {URL_MAP as URL_CLIENT_MAP} from './apiUrl.client'

export const URL_MAP = {
  LOG_OUT: API + URL_CLIENT_MAP.LOG_OUT,
  AUTHENTICATE: API + URL_CLIENT_MAP.AUTHENTICATE,
  GET_PROFILE: API + URL_CLIENT_MAP.GET_PROFILE,

  GET_EMPLOYER_WORKING_DAYS: API + URL_CLIENT_MAP.GET_EMPLOYER_WORKING_DAYS,
}
