FROM node:latest AS html
RUN apt-get update && apt-get install -y --no-install-recommends build-essential autoconf libtool pkg-config && apt-get clean

FROM html AS html-release
WORKDIR /html
RUN mkdir build
COPY tsconfig.json ./
COPY package*.json ./
RUN yarn install
COPY webpack.config.js ./
COPY . .
RUN yarn run build

FROM html AS html-development
WORKDIR /html
EXPOSE 3000
CMD ["yarn", "start"]
