FROM node:latest AS html
RUN apt-get update && apt-get install -y --no-install-recommends build-essential autoconf libtool pkg-config && apt-get clean

# Etap 1: Base
FROM html AS html-release
WORKDIR /html
RUN mkdir build
COPY tsconfig.json ./
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etap 2: Development
FROM html AS html-development
WORKDIR /html
EXPOSE 3000
CMD ["npm", "start"]
